version: 2

models:
  - name: yellow_taxi_raw
    description: Raw yellow taxi trip data
    columns:
      - name: tpep_pickup_datetime
        description: Pickup datetime in America/New_York timezone
        tests:
          - not_null
          - columns_equal:
              arguments:
                column2: tpep_dropoff_datetime

      - name: tpep_dropoff_datetime
        description: Dropoff datetime in America/New_York timezone
        tests:
          - not_null

      - name: payment_type
        description: Payment type code
        tests:
          - accepted_values:
              arguments:
                values: [0, 1, 2, 3, 4, 5, 6]
      - name: fare_amount
        description: Fare amount in USD
        tests:
          - not_null
          - amount_positive

      - name: total_amount
        description: Total amount in USD
        tests:
          - not_null
          - amount_positive

# NOTE: columns_equal test example usage
# To validate two columns are equal, use:
#   - name: calculated_total
#     tests:
#       - columns_equal:
#           arguments:
#             column2: stored_total
# This validates that calculated_total = stored_total
