version: 2

seeds:
  - name: zipcodes_us
    description: United States zipcodes reference data with geographic information
    columns:
      - name: country_code
        description: ISO 3166-1 alpha-2 country code (e.g., US)
        data_tests:
          - not_null

      - name: zipcode
        description: United States postal ZIP code
        data_tests:
          - not_null
          - unique

      - name: place
        description: City or place name
        data_tests:
          - not_null

      - name: state
        description: Full state name (e.g., Alaska)
        data_tests:
          - not_null

      - name: state_code
        description: Two-letter state abbreviation (e.g., AK)
        data_tests:
          - not_null

      - name: province
        description: Province or region name within state
        data_tests: []

      - name: province_code
        description: Numeric code for province/region

      - name: community
        description: Community or township name

      - name: community_code
        description: Code for community/township

      - name: latitude
        description: Geographic latitude coordinate
        data_tests:
          - not_null

      - name: longitude
        description: Geographic longitude coordinate
        data_tests:
          - not_null
